kind: pipeline
name: default

type: docker
steps:
  - name: lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run --enable-all
  - name: test
    image: golang
    commands:
      - sleep 35
      - go run setupdb
      - go test -v ./...
    environment:
      - URLSHORTENER_DATABASE_HOST: database
  - name: docker
    image: plugins/docker
    settings:
      username: rahaalvani
      password:
        from_secret: docker_password
      repo: rahaalvani/urlshortener
      dockerfile: ./Dockerfile
services:
  - name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: koochooloo
