kind: pipeline
name: default

type: docker
steps:
  - name: lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run --enable-all
  - name: test
    image: golang
    commands:
      - go test -v ./...
  - name: docker
    image: plugins/docker
    volumes:
      - ./Dockerfile:/var/lib/docker/Dockerfile
    settings:
      username: rahaalvani
      password:
        from_secret: docker_password
      repo: urlshortener
      dockerfile: .
