global:
  scrape_interval: 1m
  scrape_timeout: 10s

scrape_configs:
  - job_name: urlshortener
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - 172.17.0.1:8081