package store

import (
	"database/sql"
	"log"
	"time"

	"github.com/elahe-dastan/urlShortener/generator"
	"github.com/elahe-dastan/urlShortener/metric"
	"github.com/elahe-dastan/urlShortener/model"
	"github.com/prometheus/client_golang/prometheus"
)

type TinyURL interface {
}

type ShortURL struct {
	DB        *sql.DB
	Length    int
	Histogram prometheus.Histogram
}

func NewShortURL(d *sql.DB) ShortURL {
	return ShortURL{DB: d,
		Histogram: metric.NewHistogram("choosing_short_url_histogram")}
}

// Connects to the database and saves all the random short urls generated by the key generator service in it
func (url ShortURL) Save() {
	_, err := url.DB.Exec("CREATE TABLE IF NOT EXISTS short_url (" +
		"url VARCHAR PRIMARY KEY," +
		"is_used boolean NOT NULL" +
		");")
	if err != nil {
		log.Fatal("Cannot create map table due to the following error", err.Error())
	}

	generator.Generate(url.DB, url.Length)
}

func (url ShortURL) Choose() string {
	var selectedURL model.ShortURL

	start := time.Now()

	defer func() {
		duration := time.Since(start)
		url.Histogram.Observe(duration.Seconds())
	}()

	url.DB.QueryRow("UPDATE short_url SET is_used = $1 WHERE url = "+
		"(SELECT url FROM short_url WHERE is_used = $2 LIMIT 1 FOR UPDATE) "+
		"RETURNING *;", true, false).Scan(&selectedURL.URL, &selectedURL.IsUsed) //O(lgn)

	return selectedURL.URL
}
